### ISSUE TITLE
KataGo v1.16.3 cuGetProcAddress_v2 Returns CUDA_ERROR_NOT_FOUND for D3D/WGL Functions and cuGraphInstantiateWithParams_ptsz

### ISSUE THREAD

**Issue by KurococLiu** [vosen/ZLUDA#521]
### zluda_trace logs (tarball/zip file)

[zluda_log_katago.zip](https://github.com/user-attachments/files/22453333/zluda_log_katago.zip)

### Description

Description

When running KataGo (version katago-v1.16.3-cuda12.1-cudnn8.9.7-windows-x64) with ZLUDA as the CUDA compatibility layer on an AMD Radeon RX 7800 XT, the cuGetProcAddress_v2 function returns CUDA_ERROR_NOT_FOUND for several functions, primarily Direct3D (D3D9, D3D10, D3D11) and WGL interoperability functions, as well as cuGraphInstantiateWithParams_ptsz. Additionally, an empty symbol query (symbol: "") fails, which may indicate a minor issue in the application.

Expected Behavior

All queried CUDA functions should return CUDA_SUCCESS with valid function pointers (pfn), including graphics interoperability functions if supported by ZLUDA. KataGo should fully utilize GPU acceleration for neural network inference and self-play training without errors or performance degradation.

Actual Behavior

Most core CUDA functions (e.g., cuInit, cuMemcpy, cuLaunchKernel) are loaded successfully with CUDA_SUCCESS.

Graphics interoperability functions (e.g., cuWGLGetDevice, cuD3D11GetDevice, cuD3D9GetDevice) fail with CUDA_ERROR_NOT_FOUND, returning pfn: 0x0.

The function cuGraphInstantiateWithParams_ptsz fails with CUDA_ERROR_NOT_FOUND, which may impact CUDA Graph functionality.

An empty symbol query (symbol: "") fails with CUDA_ERROR_NOT_FOUND, which is expected but could indicate a minor bug in KataGo's function querying logic.

### Steps to reproduce

1. Download KataGo v1.16.3 for Windows with Zluda 5-preview.136.
2. Extract the zip file to a directory (e.g., C:\KataGo).
3. Download a pre-trained model (e.g., from https://katagotraining.org/) and place it in the KataGo directory (e.g., kata1-b18c384nbt-20230523.bin.gz).
4. Copy nvcuda.dll(rename to cublas64_12.dll) and cudnn64_9.dll(rename to cudnn64_8.dll) to the KataGo directory
5. Run KataGo with GTP mode:
```
cd C:\KataGo
katago.exe gtp -model kata1-b18c384nbt-20230523.bin.gz -config gtp_example.cfg
```

### ZLUDA version

5-preview.136

### Operating System

Windows 11 (version 24H2 26100.3476)

### GPU

AMD Radeon RX 7800 XT

**Comment by vosen** [comment]
Thanks for taking your time to collect traces. The `CUDA_ERROR_NOT_FOUND` in the log are benign.
I've reproed your set up and the logs are cut off due to poor Windows support in ZLUDA. We will be working on improving it (#522) so we can get all the necessary logs, but I can't give any timelines.
Is it possible for you to collect the logs on Linux in the meantime?

**Comment by KurococLiu** [comment]
Thanks for the response @vosen. As requested, I've collected the trace logs on Linux (WSL Ubuntu 24.04 LTS). The cuDNN panic persists with "not yet implemented" in zluda_dnn/src/impl.rs:25:5. Attached katago_log.zip containing trace logs, full backtrace.

Steps to reproduce on Linux:
- Environment: WSL2 Ubuntu 24.04 LTS, AMD Radeon RX 7800 XT, ROCm 6.4.2-120, ZLUDA 5-preview.139.
- Command: LD_LIBRARY_PATH="/mnt/f/Go/wsl/ZLUDA:$LD_LIBRARY_PATH" ./katago benchmark -model [model path] -config config.cfg
- GPU detected as "AMD Radeon RX 7800 XT [ZLUDA]", but crashes during neural net initialization.

[katago_log.zip](https://github.com/user-attachments/files/22570136/katago_log.zip)

**Comment by vosen** [comment]
Thanks, I've traced it and this is the list of CUDA functions we need for that workload
```
cublasCreate_v2
cublasHgemm
cudnnConvolutionForward
cudnnCreateFilterDescriptor
cudnnDestroyConvolutionDescriptor
cudnnSetTensor4dDescriptor
cudnnDestroyTensorDescriptor
cudnnDestroyFilterDescriptor
cudnnCreate
cublasSgemm_v2
cudnnDestroy
cudnnSetFilter4dDescriptor
cudnnSetConvolutionMathType
cublasDestroy_v2
cudnnGetConvolutionForwardWorkspaceSize
cudnnGetConvolutionForwardAlgorithm_v7
cudnnGetErrorString
cudnnSetConvolution2dDescriptor
cudnnCreateTensorDescriptor
cudnnCreateConvolutionDescriptor
```
In addition we need to split cudnn8 and cudnn9 (tey are slightly incompatible). I'll bump this issue when these land in ZLUDA

**Comment by KurococLiu** [comment]
> Thanks, I've traced it and this is the list of CUDA functions we need for that workload
> 
> ```
> cublasCreate_v2
> cublasHgemm
> cudnnConvolutionForward
> cudnnCreateFilterDescriptor
> cudnnDestroyConvolutionDescriptor
> cudnnSetTensor4dDescriptor
> cudnnDestroyTensorDescriptor
> cudnnDestroyFilterDescriptor
> cudnnCreate
> cublasSgemm_v2
> cudnnDestroy
> cudnnSetFilter4dDescriptor
> cudnnSetConvolutionMathType
> cublasDestroy_v2
> cudnnGetConvolutionForwardWorkspaceSize
> cudnnGetConvolutionForwardAlgorithm_v7
> cudnnGetErrorString
> cudnnSetConvolution2dDescriptor
> cudnnCreateTensorDescriptor
> cudnnCreateConvolutionDescriptor
> ```
> 
> In addition we need to split cudnn8 and cudnn9 (tey are slightly incompatible). I'll bump this issue when these land in ZLUDA

Thanks again for the update. To help move things forward, is there anything else I can do right now to assist with improvements, like providing more traces or testing specific setups?
Also, once these changes land, will the updated version support running on both Windows and Linux platforms seamlessly? If a version that resolves this issue gets released, could you let me know so I can test it and provide feedback?

**Comment by vosen** [comment]
I'll let you know when we have those features merged. We automatically build a new binary package after every change that gets merged, so you will be able to use that.
It won't be seamless on Windows. While it should work, there are two problems with the integration:
* Aligning all the libraries (nvcuda.dll, rocblas.dll, etc)  in the right directory so they get loaded. This can be resolved manually
* MIOpen. Last time I checked it's not shipped with HIP SDK. I think there are unofficial Windows builds floating around. It's on you to find it and put in the right path

**Comment by vosen** [comment]
Small update: it does not look too hard to implement and I started working on it (#541), but I hit some crashes in MIOpen and it's going to take me time to figure out if there's something wrong with either ZLUDA or MIOpen

**Comment by KurococLiu** [comment]
Thanks for the heads-up and for starting the implementation in #541 — really appreciate the progress!
To answer your earlier points:

- Anything I can do now? If you need additional traces (Windows or WSL), different workloads, or help testing intermediate builds, just let me know — happy to assist.
- Dual-platform support: Got it, Linux should be seamless once merged, and Windows will work with manual library placement. I’m fine handling the nvcuda.dll/rocblas.dll setup and can hunt down an unofficial MIOpen Windows build if needed.
- Notify on release: Yes, please ping me when a new binary package drops with these fixes. I’ll test it on both Windows 11 (native) and WSL2 Ubuntu with the RX 7800 XT, and provide detailed logs/feedback (including any MIOpen-related crashes).

Thanks again for driving this forward!

**Comment by mmis1000** [comment]
@KurococLiu it seems there is nightly MIOpen Windows build now. https://github.com/ROCm/TheRock/blob/main/RELEASES.md 

The call signature is slightly incompatible due to https://github.com/ROCm/hipBLAS/issues/753 . So it will require some update of zluda itself.

**Comment by vosen** [comment]
I've got good news and bad news.

Good news is that with the #541 merged katago should work.

Bad news is that it's excruciatingly slow for reasons that are outside of our control. Here's a profiling output:

Name | Wall duration | Self duration | Avg Wall duration | Occurrences
-- | -- | -- | -- | --
naive_conv_ab_nonpacked_fwd_nhwc_half_double_half.kd | 202.0s | 202.0s | 6.567ms | 30758
__amd_rocclr_copyBuffer.kd | 72.52ms | 72.51ms | 4.767µs | 15210
Op4dTensorLite.kd | 46.04ms | 46.04ms | 3.242µs | 14196
applyCScaleBiasNHWCMishScale8HalfKernel(__half const*, __half*, __half const*, __half const*, int, int) (.kd) | 40.81ms | 40.81ms | 1.341µs | 30420
Cijk_Ailk_Bljk_HHS_BH_UserArgs_MT16x16x64_MI16x16x1_SN_LDSB0_AFC0_AFEM1_AFEM1_ASEM1_CLR1_CADS0_DTVA0_DTVB0_EPS0_FDSI0_GRPM1_GRVWA8_GRVWB8_GSUAMB_GLS0_ISA1201_IU1_K1_LBSPPA256_LBSPPB256_LBSPPM0_LPA16_LPB16_LPM0_LRVW8_LWPMn1_MIAV1_MIWT1_1_MO40_NTn1_NTA0_NTB0_NTC0_NTD0_NTM0_NEPBS0_NLCA1_NLCB1_ONLL1_PGR0_PLR0_PKA0_SIA3_SS0_SPO0_SRVW0_SSO0_SVW8_SK0_SKXCCM0_TLDS0_ULSGRO0_USL1_UIOFGRO0_USFGROn1_VSn1_VWA1_VWB1_WSGRA0_WSGRB0_WS32_WG16_2_1.kd | 11.55ms | 11.55ms | 6.834µs | 1690
Cijk_Ailk_Bljk_SB_Bias_HAS_SAV_UserArgs_MT16x16x16_SN_LDSB0_AFC1_AFEM1_AFEM1_ASEM1_CLR0_CADS0_DTVA0_DTVB0_EPS1_FDSI0_GRPM1_GRVWA1_GRVWB1_GSUAMB_GLS0_ISA1201_IU1_K1_LBSPPA0_LBSPPB0_LBSPPM0_LPA0_LPB0_LPM0_LRVW1_LWPMn1_MIAV0_MO40_NTn1_NTA0_NTB0_NTC0_NTD0_NTM0_NEPBS0_NLCA1_NLCB1_ONLL1_PGR1_PLR0_PKA0_SIA1_SS0_SPO0_SRVW0_SSO0_SVW1_SK0_SKXCCM0_TT2_2_TLDS0_ULSGRO0_USL1_UIOFGRO0_USFGROn1_VSn1_VWA1_VWB1_WSGRA0_WSGRB0_WS64_WG8_8_1.kd | 6.609ms | 6.609ms | 7.821µs | 845
Cijk_Ailk_Bljk_SB_Bias_HAS_SAV_UserArgs_MT16x16x8_SN_LDSB0_AFC1_AFEM1_AFEM1_ASEM1_CLR0_CADS0_DTVA0_DTVB0_EPS1_FDSI0_GRPM1_GRVWA1_GRVWB1_GSUAMB_GLS0_ISA1201_IU1_K1_LBSPPA0_LBSPPB0_LBSPPM0_LPA0_LPB0_LPM0_LRVW1_LWPMn1_MIAV0_MO40_NTn1_NTA0_NTB0_NTC0_NTD0_NTM0_NEPBS0_NLCA1_NLCB1_ONLL1_PGR1_PLR0_PKA0_SIA1_SS0_SPO0_SRVW0_SSO0_SVW1_SK0_SKXCCM0_TT2_2_TLDS0_ULSGRO0_USL1_UIOFGRO0_USFGROn1_VSn1_VWA1_VWB1_WSGRA0_WSGRB0_WS64_WG8_8_1.kd | 3.881ms | 3.881ms | 22.96µs | 169
addNCBiasInplaceNHWCHalfKernel(__half*, __half const*, int, int) (.kd) | 2.231ms | 2.231ms | 1.320µs | 1690
naive_conv_ab_nonpacked_fwd_nhwc_float_double_float.kd | 1.631ms | 1.631ms | 9.652µs | 169
copyFromHalfKernel(__half const*, float*, int) (.kd) | 1.453ms | 1.453ms | 1.719µs | 845
gPoolChannelsNHWCHalfKernel(__half const*, __half*, int, int, float const*, int) (.kd) | 1.076ms | 1.076ms | 707ns | 1521
gPoolChannelsNHWCKernel(float const*, float*, int, int, float const*, int) (.kd) | 757.5µs | 757.5µs | 4.482µs | 169
valueHeadPoolChannelsNHWCKernel(float const*, float*, int, int, int, float const*) (.kd) | 727.7µs | 727.7µs | 4.305µs | 169
copyToHalfKernel(float const*, __half*, int) (.kd) | 618.4µs | 618.4µs | 1.829µs | 338
addCBiasInplaceNCKernelMishScale8(float*, float const*, int, int) (.kd) | 596.6µs | 596.6µs | 1.764µs | 338
addCBiasInplaceNCKernel(float*, float const*, int, int) (.kd) | 524.5µs | 524.5µs | 1.551µs | 338
applyCScaleBiasNHWCMishScale8Kernel(float const*, float*, float const*, float const*, int, int) (.kd) | 475.1µs | 475.1µs | 2.811µs | 169
sumChannelsNCHWKernel(float const*, float*, int, int, float) (.kd) | 430.4µs | 430.4µs | 2.546µs | 169
void extractChannel0KernelNHWC<__half>(__half const*, __half*, int, int) (.kd) | 309.1µs | 309.1µs | 1.829µs | 169
addNCBiasInplaceNHWCKernel(float*, float const*, int, int) (.kd) | 307.3µs | 307.3µs | 1.818µs | 169

Everything that ends with `(.kd)` is CUDA code compiled by ZLUDA, everything that ends with `.kd`  is either HIP runtime or MIOpen. I'm not really familiar with MIOpen codebase, but as far as I understand  `naive_conv_ab_nonpacked_fwd_nhwc_half_double_half` is an unoptimized convolution for fp16 data that does computation in fp64 (⁉️). It's probably tens or hundreds time slower than even a sligthly optimized versions.
Unfortunately that's as much as I can do for cudnn backend. You might consider raising the issue with MIOpen. tensorrt backend might work eventually; but even if it does, it's not a long term solution
